[project]
name = "llm-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ahmed Ehsan", email = "ahmedehsansaad@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=2.53.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[project.scripts]
llm-zoomcamp = "llm_zoomcamp:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
